### ISSUE TITLE
Weird rendering of Brightcove video player

### ISSUE THREAD

**Issue by natea** [raccoongang/xblock-video#226] opened 2017-05-04 21:04 UTC
The video player that appears in the LMS seems to be missing elements or the elements are mispositioned. See attached screenshot.

<img width="999" alt="unit_unit___video_xblock_testing_course___studio" src="https://cloud.githubusercontent.com/assets/118984/25724926/4830bbc4-30e3-11e7-90f7-37ab8728d0e4.png">

**Comment by z4y4ts** [comment] 2017-05-04 21:19
Wow, that's really messed up. Looks like css are missing completely.

Can you please provide more details:
* What version is installed?
* What are the xblock settings?

I'll try to reproduce that on our instance tomorrow.

**Comment by natea** [comment] 2017-05-04 21:23
How can I find the version of the XBlock? And where do I find the XBlock settings?

**Comment by natea** [comment] 2017-05-04 21:24
I think we're using 0.6.5 according to this:
https://github.com/appsembler/xblock-video/blob/master/setup.py#L7

**Comment by natea** [comment] 2017-05-04 21:27
More specifically, here is the commit that's installed:

```
EDXAPP_EXTRA_REQUIREMENTS:
  - name: 'git+https://github.com/edx-solutions/xblock-brightcove.git@b8d13b6b3b0c3c31a3334cf887b448076dc2bad8#egg=xblock-brightcove'
```

**Comment by natea** [comment] 2017-05-04 21:28
These are the XBlock settings (with secrets removed):

```
EDXAPP_XBLOCK_SETTINGS:
  "video_xblock": { 
    "threeplaymedia_apikey": "xxxxxxxxxx",
    "account_id": "xxxxxxxxxxx"
  }
```

**Comment by z4y4ts** [comment] 2017-05-04 21:29
If you've installed the latest code, then yes, it's 0.6.5

`github.com/edx-solutions/xblock-brightcove` is not our XBlock.

To see XBlock settings click on the "Edit" button above the video.

I need at least video url, account_id and player_id (if set) and all other settings if you changed anything in the advanced tab.

**Comment by natea** [comment] 2017-05-04 21:56
I'm seeing this in the web developer console:

```
Invalid 'X-Frame-Options' header encountered when loading 'https://studio.staging-openedx.learning.intersystems.com/preview/xblock/blo…VT101+2017_Spring+type@video_xblock+block@c209e18de3f4448bbb391c0c676994e1': 'ALLOW' is not a recognized directive. The header will be ignored.
VM8281:30 Data processed successfully.
index.min.js:19 GET https://edge.api.brightcove.com/playback/v1/accounts/90843153001/videos/5186070740001 404 (Not Found)
h @ index.min.js:19
f @ index.min.js:19
h @ index.min.js:19
q @ index.min.js:20
w @ index.min.js:20
I @ index.min.js:20
(anonymous) @ index.min.js:9
ba @ index.min.js:9
n @ index.min.js:20
(anonymous) @ index.min.js:20
(anonymous) @ index.min.js:1
(anonymous) @ index.min.js:1
```

**Comment by natea** [comment] 2017-05-04 23:42
video url: https://studio.brightcove.com/products/videocloud/media/videos/5186070740001
account_id: 90843153001  (this is what appears in Studio, although when i go to "account information, it says my account ID is 5184446939001)
player_id: not set

When I replaced the account ID from '90843153001' to '5184446939001', then the video player renders properly! The first account number is our customer's account ID, and must be getting read from server-vars.yml, whereas the second account number is the one I'm using for testing, and it's an Appsembler Brightcove account.

So it appears that when you try to use an account number that you don't own, that's what causes the weird video player rendering to occur.

**Comment by z4y4ts** [comment] 2017-05-05 17:14
I can confirm this issue.

Wrong Brightcove account ID breaks player UI. We'll need to prioritize this.

**Comment by bryanlandia** [comment] 2018-01-20 01:10
@natea Can you close this issue, plz? It's been resolved.

**Comment by bryanlandia** [comment] 2018-01-26 19:41
@natea ping.

**Closed** 2018-01-27 21:42 UTC
